title: "koala@Home:$"
description: "The Koala Terminal: Navigating the syntax of continuous learning."
url: "https://zenki209.github.io"
baseurl: "/myblog"

remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

markdown: kramdown
kramdown:
  auto_ids: true


permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Admin"

include:
  - css
  - js
  - _images

author: Admin